/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descansoApp.interfaz;

import descansoApp.dominio.Ciudad;
import descansoApp.dominio.Sistema;
import descansoApp.herramientas.TipoCA;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class pnlAgregarCiudad extends javax.swing.JPanel {
    
    ArrayList<String> imagenes;
    private Sistema modelo;
    private JFrame miVentana;
    private JFileChooser chooser;
    private String route;
    private Ciudad ciudad;

    /**
     * Creates new form pnlAgregarCiudad
     */
    public pnlAgregarCiudad(Sistema unModelo, JFrame unContenedor) {
        initComponents();
        chooser = new JFileChooser();
        modelo = unModelo;
        miVentana = unContenedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnAdjuntarImagenes = new javax.swing.JButton();
        btnAgregarAlojamiento = new javax.swing.JButton();
        btnAgregarComer = new javax.swing.JButton();
        btnAgregarQueHacer = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAInfoGeneral = new javax.swing.JTextArea();
        btnGuardarCiudad = new javax.swing.JButton();

        btnAdjuntarImagenes.setText("Adjuntar Imagenes");
        btnAdjuntarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarImagenesActionPerformed(evt);
            }
        });

        btnAgregarAlojamiento.setText("Agregar Alojamiento");
        btnAgregarAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlojamientoActionPerformed(evt);
            }
        });

        btnAgregarComer.setText("Agregar Comer");
        btnAgregarComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComerActionPerformed(evt);
            }
        });

        btnAgregarQueHacer.setText("Agregar Que hacer");

        jButton5.setText("Agregar Mapa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tfNombre.setText("Nombre");

        tfDescripcion.setText("Descripcion");
        tfDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDescripcionActionPerformed(evt);
            }
        });

        tAInfoGeneral.setColumns(20);
        tAInfoGeneral.setRows(5);
        tAInfoGeneral.setText("Info General");
        jScrollPane1.setViewportView(tAInfoGeneral);

        btnGuardarCiudad.setText("Guardar");
        btnGuardarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarCiudad)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnAgregarAlojamiento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAgregarComer)
                            .addGap(18, 18, 18)
                            .addComponent(btnAgregarQueHacer))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdjuntarImagenes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdjuntarImagenes)))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(34, 34, 34)
                .addComponent(btnGuardarCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAlojamiento)
                    .addComponent(btnAgregarComer)
                    .addComponent(btnAgregarQueHacer))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComerActionPerformed
        PopUp p= new PopUp();
        
        p.add(new pnlAgregarComercioActividad(modelo, p, ciudad,TipoCA.estGastronomico));
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btnAgregarComerActionPerformed

    private void tfDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescripcionActionPerformed

    private void btnGuardarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCiudadActionPerformed
        this.ciudad.setNombre(tfNombre.getText());
        this.ciudad.setDescripcion(tfDescripcion.getText());
        this.ciudad.setDescripcion(tfDescripcion.getText());
        this.ciudad.agregarImagen(route);
        modelo.agregarCiudad(this.ciudad);
    }//GEN-LAST:event_btnGuardarCiudadActionPerformed

    private void btnAdjuntarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarImagenesActionPerformed
        /*  int returnVal = chooser.showDialog(pnlAgregarCiudad.this,"Attach" );
        chooser.setVisible(true);
        File[] files = chooser.getSelectedFiles();
        String a = "'a";
         */
        
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setAcceptAllFileFilterUsed(false);
        
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
            route = chooser.getSelectedFile() + "";
            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }
        //  File[] filesInDirectory = chooser.getCurrentDirectory().listFiles();
    }//GEN-LAST:event_btnAdjuntarImagenesActionPerformed

    private void btnAgregarAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarAlojamientoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    public void actionPerformed(ActionEvent e) {
        //Handle open button action.
        // if (e.getSource() == btnAdjuntarImagenes) {
        //  int returnVal = fc.showOpenDialog(FileChooserDemo.this);

        //    if (returnVal == JFileChooser.APPROVE_OPTION) {
        //      File file = fc.getSelectedFile();
        //This is where a real application would open the file.
        //    log.append("Opening: " + file.getName() + "." + newline);
        //  } else {
        //  log.append("Open command cancelled by user." + newline);
        //  }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntarImagenes;
    private javax.swing.JButton btnAgregarAlojamiento;
    private javax.swing.JButton btnAgregarComer;
    private javax.swing.JButton btnAgregarQueHacer;
    private javax.swing.JButton btnGuardarCiudad;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tAInfoGeneral;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
