/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descansoApp.interfaz;

import descansoApp.dominio.Ciudad;
import descansoApp.dominio.Sistema;
import descansoApp.herramientas.TipoCA;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class pnlAgregarComercioActividad extends javax.swing.JPanel {
    private Ciudad ciudad;

    /**
     * Creates new form pnlAgregarComercioActividad
     */
    public pnlAgregarComercioActividad(Sistema unModelo, JFrame unContenedor, Ciudad unaCiudad, TipoCA tipoCA) {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFNombre = new javax.swing.JTextField();
        tFDetalles = new javax.swing.JTextField();
        tFCategoria = new javax.swing.JTextField();
        tFUbicacion = new javax.swing.JTextField();
        tFTelefono = new javax.swing.JTextField();
        tFWebLink = new javax.swing.JTextField();
        tFPrecio = new javax.swing.JTextField();
        btnAdjuntarImagenes = new javax.swing.JButton();
        btnGuardarCA = new javax.swing.JButton();

        tFNombre.setText("Nombre");

        tFDetalles.setText("Detalles");
        tFDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFDetallesActionPerformed(evt);
            }
        });

        tFCategoria.setText("Categoria");

        tFUbicacion.setText("Ubicacion");

        tFTelefono.setText("Telefono");
        tFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFTelefonoActionPerformed(evt);
            }
        });

        tFWebLink.setText("Web");

        tFPrecio.setText("Precio");

        btnAdjuntarImagenes.setText("Adjuntar Imagenes");

        btnGuardarCA.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdjuntarImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFTelefono)
                            .addComponent(tFWebLink, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFNombre)
                            .addComponent(tFDetalles)
                            .addComponent(tFCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(tFUbicacion))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(tFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tFUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFWebLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdjuntarImagenes)
                .addGap(31, 31, 31)
                .addComponent(btnGuardarCA)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tFDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFDetallesActionPerformed

    private void tFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntarImagenes;
    private javax.swing.JButton btnGuardarCA;
    private javax.swing.JTextField tFCategoria;
    private javax.swing.JTextField tFDetalles;
    private javax.swing.JTextField tFNombre;
    private javax.swing.JTextField tFPrecio;
    private javax.swing.JTextField tFTelefono;
    private javax.swing.JTextField tFUbicacion;
    private javax.swing.JTextField tFWebLink;
    // End of variables declaration//GEN-END:variables
}
