/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descansoApp.interfaz;

import descansoApp.dominio.Ciudad;
import descansoApp.dominio.ComercioActividad;
import descansoApp.dominio.Sistema;
import descansoApp.herramientas.TipoCA;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlAgregarComercioActividad extends javax.swing.JPanel {
    private Ciudad ciudad;
    private TipoCA tipoCA;
    private ArrayList<String> errores;
    private JFrame miVentana;
    private Sistema miModelo;
    private ArrayList<String> rutasImagenes;
    

    /**
     * Creates new form pnlAgregarComercioActividad
     */
    public pnlAgregarComercioActividad(Sistema unModelo, JFrame unContenedor) {
        initComponents();
        miVentana = unContenedor;
        miModelo = unModelo;
        cBCiudad.setModel(new DefaultComboBoxModel(unModelo.getListaCiudades().toArray()));
        String[] tipoCAArray ={"Alojamiento", "E. Gastronomico", "Actividad", "Otros..."};
        cBTipoCA.setModel(new DefaultComboBoxModel(tipoCAArray));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFNombre = new javax.swing.JTextField();
        tFDetalles = new javax.swing.JTextField();
        tFCategoria = new javax.swing.JTextField();
        tFUbicacion = new javax.swing.JTextField();
        tFTelefono = new javax.swing.JTextField();
        tFWebLink = new javax.swing.JTextField();
        tFPrecio = new javax.swing.JTextField();
        btnAdjuntarImagenes = new javax.swing.JButton();
        btnGuardarCA = new javax.swing.JButton();
        tFHorario = new javax.swing.JTextField();
        cBTipoCA = new javax.swing.JComboBox<>();
        cBCiudad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tFNombre.setText("Nombre");
        add(tFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 178, 30));

        tFDetalles.setText("Detalles");
        tFDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFDetallesActionPerformed(evt);
            }
        });
        add(tFDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 178, 30));

        tFCategoria.setText("Categoria");
        add(tFCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 178, 30));

        tFUbicacion.setText("Ubicacion");
        add(tFUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 178, 30));

        tFTelefono.setText("Telefono");
        tFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFTelefonoActionPerformed(evt);
            }
        });
        add(tFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 178, 30));

        tFWebLink.setText("Web");
        add(tFWebLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 178, 30));

        tFPrecio.setText("Precio");
        tFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPrecioActionPerformed(evt);
            }
        });
        add(tFPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 178, 30));

        btnAdjuntarImagenes.setText("Adjuntar Imagenes");
        btnAdjuntarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarImagenesActionPerformed(evt);
            }
        });
        add(btnAdjuntarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 178, 30));

        btnGuardarCA.setText("Guardar");
        btnGuardarCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCAActionPerformed(evt);
            }
        });
        add(btnGuardarCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 178, 30));

        tFHorario.setText("Horario");
        add(tFHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 178, 30));

        cBTipoCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cBTipoCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 178, 30));

        cBCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cBCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 178, 30));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Nuevo Comercio/Actividad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descansoApp/imagenes/fondoVentanaVertical.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void tFDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFDetallesActionPerformed

    private void tFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFTelefonoActionPerformed

    private void btnGuardarCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCAActionPerformed
        if (verificarCampos()){
            ComercioActividad comercioActividad = new ComercioActividad(tFNombre.getText(), tFDetalles.getText(), ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString()), tFCategoria.getText(),tFHorario.getText(), tFUbicacion.getText(), tFTelefono.getText(), tFWebLink.getText(), tFPrecio.getText());
            if(this.rutasImagenes.size()>0){
                for(int i =0; i<this.rutasImagenes.size();i++){
                    comercioActividad.agregarImagenDesdeRuta(this.rutasImagenes.get(i));
                }
            }
            String nombreCiudad = cBCiudad.getSelectedItem().toString();
            Ciudad ciudadAux = new Ciudad(nombreCiudad, "");
            int indiceCiudad = miModelo.getListaCiudades().indexOf(ciudadAux);
            Ciudad laCiudad = miModelo.getListaCiudades().get(indiceCiudad);
            laCiudad.agregarComercioActividad(ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString()), comercioActividad);
            JOptionPane.showMessageDialog(this, ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString())+" correctamente agregado");
            miVentana.dispose();
            
        }else{
            String mensaje = "Debe de completar los siguientes campos: ";
            for (int i =0;i<errores.size();i++){
                if (i+1==errores.size()){
                    mensaje+= errores.get(i) + ".";
                }else{
                     mensaje+= errores.get(i) + ", ";
                }
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }//GEN-LAST:event_btnGuardarCAActionPerformed

    private void btnAdjuntarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarImagenesActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setMultiSelectionEnabled(true);
        chooser.setAcceptAllFileFilterUsed(false);
        rutasImagenes = new ArrayList<>();
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
          //  route = chooser.getSelectedFile() + "";
            File [] files = chooser.getSelectedFiles();
            for (int i =0;i<files.length;i++){
                this.rutasImagenes.add(files[i].getPath());
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btnAdjuntarImagenesActionPerformed

    private void tFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPrecioActionPerformed

    
    private boolean verificarCampos (){
        errores = new ArrayList<>();
        boolean sinErrores = true;
        
        if(tFNombre.getText().isEmpty()){
            sinErrores = false;
           errores.add("Nombre");
        }if(tFDetalles.getText().isEmpty()){
            sinErrores = false;
           errores.add("Detalles");
        }if(tFCategoria.getText().isEmpty()){
            sinErrores = false;
           errores.add("Categoria");
        }if(tFHorario.getText().isEmpty()){
            sinErrores = false;
           errores.add("Horario");
        }if(tFUbicacion.getText().isEmpty()){
            sinErrores = false;
           errores.add("Ubicacion");
        }if(tFTelefono.getText().isEmpty()){
            sinErrores = false;
           errores.add("Telefono");
        }if(tFWebLink.getText().isEmpty()){
            sinErrores = false;
           errores.add("Web Link");
        } if(tFPrecio.getText().isEmpty()){
            sinErrores = false;
           errores.add("Precio");
        } if(cBCiudad.getSelectedItem().toString().compareTo("Seleccionar Ciudad")==0){
            sinErrores = false;
            errores.add("Ciudad");
        } if(cBTipoCA.getSelectedItem().toString().compareTo("Tipo de Comercio/Actividad")==0){
            sinErrores = false;
            errores.add("ComercioActividad");
        }
        return sinErrores;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntarImagenes;
    private javax.swing.JButton btnGuardarCA;
    private javax.swing.JComboBox<String> cBCiudad;
    private javax.swing.JComboBox<String> cBTipoCA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tFCategoria;
    private javax.swing.JTextField tFDetalles;
    private javax.swing.JTextField tFHorario;
    private javax.swing.JTextField tFNombre;
    private javax.swing.JTextField tFPrecio;
    private javax.swing.JTextField tFTelefono;
    private javax.swing.JTextField tFUbicacion;
    private javax.swing.JTextField tFWebLink;
    // End of variables declaration//GEN-END:variables
}
