/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descansoApp.interfaz;

import descansoApp.dominio.Ciudad;
import descansoApp.dominio.ComercioActividad;
import descansoApp.dominio.Sistema;
import descansoApp.herramientas.TipoCA;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class pnlAgregarComercioActividad extends javax.swing.JPanel {
    private Ciudad ciudad;
    private TipoCA tipoCA;
    private ArrayList<String> errores;
    private JFrame miVentana;
    private Sistema miModelo;
    private ArrayList<String> rutasImagenes;
    

    /**
     * Creates new form pnlAgregarComercioActividad
     */
    public pnlAgregarComercioActividad(Sistema unModelo, JFrame unContenedor) {
        initComponents();
        miVentana = unContenedor;
        miModelo = unModelo;
        cBCiudad.setModel(new DefaultComboBoxModel(unModelo.getListaCiudades().toArray()));
        String[] tipoCAArray ={"alojamiento", "estGastronomico", "actividad", "otros"};
        cBTipoCA.setModel(new DefaultComboBoxModel(tipoCAArray));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tFNombre = new javax.swing.JTextField();
        tFDetalles = new javax.swing.JTextField();
        tFCategoria = new javax.swing.JTextField();
        tFUbicacion = new javax.swing.JTextField();
        tFTelefono = new javax.swing.JTextField();
        tFWebLink = new javax.swing.JTextField();
        tFPrecio = new javax.swing.JTextField();
        btnAdjuntarImagenes = new javax.swing.JButton();
        btnGuardarCA = new javax.swing.JButton();
        tFHorario = new javax.swing.JTextField();
        cBTipoCA = new javax.swing.JComboBox<>();
        cBCiudad = new javax.swing.JComboBox<>();

        tFNombre.setText("Nombre");

        tFDetalles.setText("Detalles");
        tFDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFDetallesActionPerformed(evt);
            }
        });

        tFCategoria.setText("Categoria");

        tFUbicacion.setText("Ubicacion");

        tFTelefono.setText("Telefono");
        tFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFTelefonoActionPerformed(evt);
            }
        });

        tFWebLink.setText("Web");

        tFPrecio.setText("Precio");

        btnAdjuntarImagenes.setText("Adjuntar Imagenes");
        btnAdjuntarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjuntarImagenesActionPerformed(evt);
            }
        });

        btnGuardarCA.setText("Guardar");
        btnGuardarCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCAActionPerformed(evt);
            }
        });

        tFHorario.setText("Horario");

        cBTipoCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cBCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarCA, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(btnAdjuntarImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(tFPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFTelefono)
                            .addComponent(tFWebLink, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFNombre)
                            .addComponent(tFDetalles)
                            .addComponent(tFCategoria)
                            .addComponent(tFUbicacion)
                            .addComponent(tFHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addComponent(cBTipoCA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(cBCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cBTipoCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tFHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tFUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFWebLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdjuntarImagenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCA)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tFDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFDetallesActionPerformed

    private void tFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFTelefonoActionPerformed

    private void btnGuardarCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCAActionPerformed
        if (verificarCampos()){
            ComercioActividad comercioActividad = new ComercioActividad(tFNombre.getText(), tFDetalles.getText(), ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString()), tFCategoria.getText(),tFHorario.getText(), tFUbicacion.getText(), tFTelefono.getText(), tFWebLink.getText(), tFPrecio.getText());
            if(this.rutasImagenes.size()>0){
                for(int i =0; i<this.rutasImagenes.size();i++){
                    comercioActividad.agregarImagenDesdeRuta(this.rutasImagenes.get(i));
                }
            }
            String nombreCiudad = cBCiudad.getSelectedItem().toString();
            Ciudad ciudadAux = new Ciudad(nombreCiudad, "");
            int indiceCiudad = miModelo.getListaCiudades().indexOf(ciudadAux);
            Ciudad laCiudad = miModelo.getListaCiudades().get(indiceCiudad);
            laCiudad.agregarComercioActividad(ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString()), comercioActividad);
            JOptionPane.showMessageDialog(this, ComercioActividad.getTipoCA(cBTipoCA.getSelectedItem().toString())+" correctamente agregado");
            miVentana.dispose();
            
        }else{
            String mensaje = "Debe de completar los siguientes campos: ";
            for (int i =0;i<errores.size();i++){
                if (i+1==errores.size()){
                    mensaje+= errores.get(i) + ".";
                }else{
                     mensaje+= errores.get(i) + ", ";
                }
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }//GEN-LAST:event_btnGuardarCAActionPerformed

    private void btnAdjuntarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjuntarImagenesActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setMultiSelectionEnabled(true);
        chooser.setAcceptAllFileFilterUsed(false);
        rutasImagenes = new ArrayList<>();
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
          //  route = chooser.getSelectedFile() + "";
            File [] files = chooser.getSelectedFiles();
            for (int i =0;i<files.length;i++){
                this.rutasImagenes.add(files[i].getPath());
            }
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btnAdjuntarImagenesActionPerformed

    
    private boolean verificarCampos (){
        errores = new ArrayList<>();
        boolean sinErrores = true;
        
        if(tFNombre.getText().isEmpty()){
            sinErrores = false;
           errores.add("Nombre");
        }if(tFDetalles.getText().isEmpty()){
            sinErrores = false;
           errores.add("Detalles");
        }if(tFCategoria.getText().isEmpty()){
            sinErrores = false;
           errores.add("Categoria");
        }if(tFHorario.getText().isEmpty()){
            sinErrores = false;
           errores.add("Horario");
        }if(tFUbicacion.getText().isEmpty()){
            sinErrores = false;
           errores.add("Ubicacion");
        }if(tFTelefono.getText().isEmpty()){
            sinErrores = false;
           errores.add("Telefono");
        }if(tFWebLink.getText().isEmpty()){
            sinErrores = false;
           errores.add("Web Link");
        } if(tFPrecio.getText().isEmpty()){
            sinErrores = false;
           errores.add("Precio");
        } if(cBCiudad.getSelectedItem().toString().compareTo("Seleccionar Ciudad")==0){
            sinErrores = false;
            errores.add("Ciudad");
        } if(cBTipoCA.getSelectedItem().toString().compareTo("Tipo de Comercio/Actividad")==0){
            sinErrores = false;
            errores.add("ComercioActividad");
        }
        return sinErrores;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntarImagenes;
    private javax.swing.JButton btnGuardarCA;
    private javax.swing.JComboBox<String> cBCiudad;
    private javax.swing.JComboBox<String> cBTipoCA;
    private javax.swing.JTextField tFCategoria;
    private javax.swing.JTextField tFDetalles;
    private javax.swing.JTextField tFHorario;
    private javax.swing.JTextField tFNombre;
    private javax.swing.JTextField tFPrecio;
    private javax.swing.JTextField tFTelefono;
    private javax.swing.JTextField tFUbicacion;
    private javax.swing.JTextField tFWebLink;
    // End of variables declaration//GEN-END:variables
}
